[package]
name = "litname"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0.27"
syn = { version = "2", features = [
    "full",
    "parsing",
    "proc-macro",
    "printing",
], default-features = false }
unicode-ident = "1.0.8"
